In [2]:
import tensorflow as tf

In [1]:
import numpy as np
x = np.arange(10, 20).reshape(5, 2)
print(x)

[[10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [4]:
x1 = tf.keras.layers.Dense(8)(np.arange(10).reshape(5, 2))
x2 = tf.keras.layers.Dense(8)(np.arange(10, 20).reshape(5, 2))
concatted = tf.keras.layers.Concatenate()([x1, x2])
concatted.shape

TensorShape([5, 16])

In [27]:
i = np.arange(10).reshape(5, 2)
i

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [29]:
x1 = tf.keras.layers.Dense((2))
x1(i)

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[ -0.85042644,   1.0422076 ],
       [ -3.7346778 ,   5.50214   ],
       [ -6.61893   ,   9.962072  ],
       [ -9.5031805 ,  14.422005  ],
       [-12.387432  ,  18.881937  ]], dtype=float32)>